api: add fw_rule() in lib/firewall_functions
Add generic function for create and update firewall rules

diff --git a/api/lib/firewall_functions b/api/lib/firewall_functions
--- a/api/lib/firewall_functions
+++ b/api/lib/firewall_functions
@@ -215,3 +215,44 @@ function delete_rule
     fi
 
 }
+
+#
+# Create or update a firewall rule
+# The rule is passed by $data global variable
+# Takes one argument: action to perform (create/update)
+#
+# Usage example: fw_rule create
+#
+
+function fw_rule
+{
+    if [ "$1" = "create" ]; then
+        id=$(expr $(/sbin/e-smith/db fwrules showjson | jq -r '[.[].name] | map(tonumber) | max' | sed -e 's/null/0/') + 1)
+    elif [ "$1" = "update" ]; then
+        id=$(_get id)
+    else
+        error
+    fi
+    
+    if [ -z "$(_get Time)" ]; then
+        Time=""
+    else
+        Time=$(_get_fw_object "$(_get Time)")
+    fi
+    
+    Dst=$(_get_fw_object "$(_get Dst)")
+    Src=$(_get_fw_object "$(_get Src)")
+    Service=$(_get_fw_object "$(_get Service)")
+    
+    /sbin/e-smith/db fwrules set "$id" rule Action "$(_get Action)" Log $(_get Log) \
+        Position "$(_get Position)"  Time "$Time" \
+        Dst "$Dst" Service "$Service" \
+        Src "$Src" status "$(_get status)" \
+        Description "$(_get Description)"
+    
+    if [ $? -gt 0 ]; then
+        error "SaveFailed" "check_logs"
+    else
+        success
+    fi
+}
